### ISSUE TITLE
It will keep some small dot in the ShineView

### ISSUE THREAD

**Issue by chenzj-king** [ChadCSong/ShineButton#1]
As title. When I check succes. It will some small dot in the ShineView. It look very strange.

**Comment by ChadCSong** [comment]
Do you mean small dot was keep on ShineView after you click?

**Comment by chenzj-king** [comment]
@ChadCSong 
yes. like this.

![](http://i.imgur.com/Uv0daS3.png)

**Comment by ChadCSong** [comment]
oh, I forgot remove shineView when animation ended.It's a bug. If you want to fix it, you can find ShineButton.java in source and remove ShineView on AnimationListener onAnimationEnd callback. I will fix it soon. :)

**Comment by chenzj-king** [comment]
Thanks. It work well.

**Comment by ChadCSong** [comment]
https://github.com/ChadCSong/ShineButton/commit/9b5975e6dd823c465d16ef0d319963370dd85251 Fix this problem.
