### ISSUE TITLE
setChecked

### ISSUE THREAD

**Issue by juanlabrador** [ChadCSong/ShineButton#10]
You can added a method, where setChecked don't called changeListener?? thanks. It's just paint button.

**Comment by juanlabrador** [comment]
ahhh setBtnFillColor do this.

**Comment by juanlabrador** [comment]
I need to have its status in true or false, but not called changeListener

**Comment by ChadCSong** [comment]
Can you describe your usage scenario? I'm not understand what is your status mean.

**Comment by ChadCSong** [comment]
Version 0.1.7 fixed.

**Comment by LiliaBHMabrouk** [comment]
there is no animation when setchacked is false.
I wanted to have, if one button is chacked,then the others would have the colour of the btn_colour not the btn_fill_colour.
