### ISSUE TITLE
Can't use ShineButton in a CardView

### ISSUE THREAD

**Issue by paveltech** [ChadCSong/ShineButton#11]
I want to use ShineButton into my cardview but when i introduce it into the cardview it doesn't show anything. Here is my xml code

<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/tools"
    android:id="@+id/card_game"
    android:layout_width="match_parent"
    xmlns:cardview="http://schemas.android.com/apk/res-auto"
    android:layout_height="wrap_content"
    cardview:cardUseCompatPadding="true"
    cardview:cardCornerRadius="2dp"
    cardview:cardElevation="2dp">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <ImageView
            android:id="@+id/image_view"
            android:layout_width="375dp"
            android:layout_height="160dp"
            android:layout_gravity="center_horizontal"
            android:scaleType="centerCrop" />

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="51dp"
            android:orientation="vertical">

            <TextView
                android:id="@+id/title_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="pavel"
                android:layout_margin="8dp"
                android:maxLines="3" />

            <com.sackcentury.shinebuttonlib.ShineButton
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:layout_centerInParent="true"
                android:id="@+id/po_image0"
                app:btn_color="#FF6666"
                app:btn_fill_color="#999933"
                app:siShape="@raw/heart"
                android:layout_gravity="right"
                android:layout_centerVertical="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentEnd="true"/>

            <TextView
                android:id="@+id/movie_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="robin"
                android:layout_margin="8dp"
                android:layout_alignParentBottom="true"
                />

        </RelativeLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">

        </LinearLayout>

    </LinearLayout>

</android.support.v7.widget.CardView>

**Comment by ChadCSong** [comment]
I can use it normally. It works well on cardView.

![screenshot_2016-08-26-17-32-45_com miui gallery](https://cloud.githubusercontent.com/assets/8023570/18000994/63ab99dc-6bb3-11e6-87a9-e1725fcf0d02.png)


here is my code

```
<android.support.v7.widget.CardView
        xmlns:card_view="http://schemas.android.com/apk/res-auto"
        android:id="@+id/card_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        card_view:cardBackgroundColor="@android:color/white"
        android:layout_marginTop="200dp"
        android:layout_centerHorizontal="true"
        android:layout_marginBottom="5dp"
        card_view:cardCornerRadius="10dp"
        card_view:cardElevation="24dp">
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <ImageView
            android:id="@+id/image_view"
            android:layout_width="375dp"
            android:layout_height="160dp"
            android:layout_gravity="center_horizontal"
            android:scaleType="centerCrop" />

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="51dp"
            android:orientation="vertical">

            <TextView
                android:id="@+id/title_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="pavel"
                android:layout_margin="8dp"
                android:maxLines="3" />

            <com.sackcentury.shinebuttonlib.ShineButton
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:layout_centerInParent="true"
                android:id="@+id/po_image8"
                app:btn_color="#FF6666"
                app:btn_fill_color="#999933"
                app:siShape="@raw/heart"
                android:layout_gravity="right"
                android:layout_centerVertical="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentEnd="true"/>

            <TextView
                android:id="@+id/movie_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="robin"
                android:layout_margin="8dp"
                android:layout_alignParentBottom="true"
                />

        </RelativeLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">


        </LinearLayout>


    </LinearLayout>
    </android.support.v7.widget.CardView>

```

**Comment by paveltech** [comment]
Sorry bro still now this is not working.

<android.support.v7.widget.CardView xmlns:card_view="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/tools"
    android:id="@+id/card_view"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    card_view:cardBackgroundColor="@android:color/white"

    android:layout_centerHorizontal="true"
    android:layout_marginBottom="5dp"
    card_view:cardCornerRadius="10dp"
    card_view:cardElevation="24dp">
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <ImageView
            android:id="@+id/image_view"
            android:layout_width="375dp"
            android:layout_height="160dp"
            android:layout_gravity="center_horizontal"
            android:scaleType="centerCrop" />

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="51dp"
            android:orientation="vertical">

            <TextView
                android:id="@+id/title_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="pavel"
                android:layout_margin="8dp"
                android:maxLines="3" />

            <com.sackcentury.shinebuttonlib.ShineButton
                android:layout_width="50dp"
                android:layout_height="50dp"
                android:layout_centerInParent="true"
                android:id="@+id/po_image8"
                app:btn_color="#FF6666"
                app:btn_fill_color="#999933"
                app:siShape="@raw/heart"
                android:layout_gravity="right"
                android:layout_centerVertical="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentEnd="true"/>

            <TextView
                android:id="@+id/movie_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="robin"
                android:layout_margin="8dp"
                android:layout_alignParentBottom="true"
                />

        </RelativeLayout>

    </LinearLayout>
</android.support.v7.widget.CardView>
![device-2016-08-26-155138](https://cloud.githubusercontent.com/assets/7562445/18001495/08020016-6ba5-11e6-9ffd-290b5e5aab03.png)

**Comment by paveltech** [comment]
I think the problem is here i am using 

    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/tools"

this into xml file

**Comment by ChadCSong** [comment]
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/tools"

Use them in any places ？remove them and try.

**Comment by paveltech** [comment]
No it's not working if you can post your hole code then it will helpful for me to solve it.

**Comment by ChadCSong** [comment]
Check out this commit https://github.com/ChadCSong/ShineButton/commit/8d7518f2b129a3af66a11ea2f22724babcd175d2
