### ISSUE TITLE
Manifest merger failed, spent many hours in it. How to fix this.

### ISSUE THREAD

**Issue by hishamMuneer** [ChadCSong/ShineButton#12]
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:processDebugManifest'.
  
  > Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:27:9-35
  > is also present at AndroidManifest.xml:27:9-35 value=(true).
  > Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:20:5-23:76 to override.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ChadCSong** [comment]
I update my gradle version few days ago and I forgot to commit 2 files. Now you can check out new commits and have a try. Thanks.

**Comment by tmdues** [comment]
I had the same issue. Adding tools:replace="label" to the manifest resolved it for me. http://stackoverflow.com/a/40306041/2345220

**Comment by hitech95** [comment]
Please remove that line on the library:
https://github.com/ChadCSong/ShineButton/blob/3624971ff6c16074f8cfe26e6666bf1c8a8dcfbb/shinebuttonlib/src/main/AndroidManifest.xml#L4

Conficts on with other app manifests that doesn't support the backup "feature".

**Comment by ChadCSong** [comment]
android:allowBackup  removed
