### ISSUE TITLE
Doesn't work when no listener are defined

### ISSUE THREAD

**Issue by BenjaminBihr** [ChadCSong/ShineButton#2]
Hi,

I have tried to use this button but it doesn't work when I just initialize button with :

`shineButton.init(getActivity());`

But when I had a listener like that, it works : 
``` java
shineButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.d("Click","Click");
            }
        }); 
```
Ps : I have tried in a activity and in a fragment

**Comment by ChadCSong** [comment]
The usage scenario I think before is show effect when you do some click. I will improve this. Thanks. :)

**Comment by ChadCSong** [comment]
https://github.com/ChadCSong/ShineButton/commit/36bade84f4f0fb1f2af7d33779e80985a4d9426d Fix it.
