### ISSUE TITLE
Please Use Tag Release

### ISSUE THREAD

**Issue by DanieleBelfiore** [ChadCSong/ShineButton#20]
Hello,
thanks for your developments.

Only one thing I would suggest to you: you could use tag release for every new release commited.

This behaviour permit to us to find more quickly the new releases and even your GitHub page is more standard for GitHub specifications.

Really appreciate that.

Thanks in advance.

![screenshot](https://cloud.githubusercontent.com/assets/10231360/20877375/845fe228-bac8-11e6-918d-ba8b43c34097.png)

**Comment by ChadCSong** [comment]
Thanks for your reminding. I will.
