### ISSUE TITLE
Animation at wrong location when using a Dialog

### ISSUE THREAD

**Issue by asafvaron90** [ChadCSong/ShineButton#25]
I gave the dialog a specific size approximately in the center of the screen and the shine animation happens on the top left corner of it and the scale+change image color happens normally where the button is located.

I think the fix would be inside showAnim.
rootView.addView(shineView, new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));

**Comment by dengue8830** [comment]
@asafvaron90 can you share more code? i have the same issue

**Comment by asafvaron90** [comment]
I will send you the code I use for the dialog.

**Comment by asafvaron90** [comment]
myDialog(Activity activity) {
    mBtnAddToFavs.init(activity); ---> this is shineButton
}
The class extends a normal Dialog (import android.app.Dialog)
dialog will open in the middle of the screen, but the shine animation will be on the top left side of the screen.

let me know how else I can help

**Comment by dengue8830** [comment]
have hoy fixed the problem? you wrote something like

rootView.addView(shineView, new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));

but i would appreciate more code for that solution

**Comment by asafvaron90** [comment]
I haven't fixed it yet, was caught up on some other things.
That part I wrote in the first comment is from your code where you init the
view.
I think the problem is there some where.

**Comment by dengue8830** [comment]
thanks bro

**Comment by ChadCSong** [comment]
I will check  this problem as soon as quickly.

**Comment by ChadCSong** [comment]
@asafvaron90 @dengue8830  Dialog view is on the top of the content view. So it was actually a bug. I'm trying to find a way to draw animation above dialog now. If you have any idea please tell me, thanks.

**Comment by fenggit** [comment]
can you share more code? i have the same issue

**Comment by shdkhan** [comment]
In my case I got same issue in some different devices. but i am using in activity. Please share some solution

**Comment by ChadCSong** [comment]
Fix this on 1.0.0 ,pls check
