### ISSUE TITLE
click quickly will load error button color

### ISSUE THREAD

**Issue by chenzj-king** [ChadCSong/ShineButton#3]
such like this. I click quickly. 

![](http://i.imgur.com/dk70ROI.gif)

![](http://i.imgur.com/tJpe7kK.png)

The last check callback is false. So the text color is right. But the btn color is error. It look like it the shakeAnimator's problem. Because shakeAnimator onAnimationStart will call `setSrcColor(color)` . I think set Animation Listener like this.  

    shakeAnimator.addListener(new Animator.AnimatorListener() {
        @Override
        public void onAnimationStart(Animator animator) {
            if (isChecked()) {
                setSrcColor(btnFillColor);
            }
        }

        @Override
        public void onAnimationEnd(Animator animator) {
            onListenerUpdate(isChecked());
        }

        @Override
        public void onAnimationCancel(Animator animator) {
            onListenerUpdate(isChecked());
        }

        @Override
        public void onAnimationRepeat(Animator animator) {

        }
    });

and do some work in the onCheck callback.

    mPariseImg.setOnCheckStateChangeListener(new ShineButton.OnCheckedChangeListener() {
        @Override
        public void onCheckedChanged(View view, boolean isCheck) {
            if (!isCheck) {
                mPariseImg.setSrcColor(getResources().getColor(R.color.doctor_push_dis_vote));
            }
        }
    });

It can do well. I think it can add to readme.

**Comment by ChadCSong** [comment]
Yes I’m actually thoughtless.  Thanks for your reminding. Earlier I want to add lock in the process of animation, but that will destroy experience of click. 
I think add control code on CallBack for custom views is not suggested. Let's find a better way~:)

**Comment by chenzj-king** [comment]
hmmm. Looking forward to your new version.

**Comment by ChadCSong** [comment]
This issue due to Animation start automatic although I called Animation.end() when I'm already setDelay on Animation.
