### ISSUE TITLE
Animation is in wrong place

### ISSUE THREAD

**Issue by linean** [ChadCSong/ShineButton#5]
Hi, after 1.3 commit, rendering problem disapppeared, but now animation is in random place on screen, not around button ;)

**Comment by searchy2** [comment]
I have this issue as well. Hope to see a fix soon!

**Comment by ChadCSong** [comment]
I'm sorry to bring this problem by last commit , seems to be a problem on draw. Thanks for your reminding ,I will fix soon.

**Comment by ChadCSong** [comment]
@linean @searchy2  Could you help me to test if problem still be there?

**Comment by linean** [comment]
For me everything works good :) only below 20 API i see white rectangle when animating :)

**Comment by searchy2** [comment]
@ChadCSong I am compiling it into my project using Gradle. Has the 0.1.3 repository been updated?

**Comment by linean** [comment]
See main page, actual is 0.1.4

**Comment by searchy2** [comment]
@ChadCSong  Thanks for the quick fix!
@linean Thanks for the quick response. The issue is fixed on my end!
