### ISSUE TITLE
[Feature Request] Configure size of shines

### ISSUE THREAD

**Issue by searchy2** [ChadCSong/ShineButton#6]
@ChadCSong Please mark this as a feature request, thank you!

Shines are sized proportionally to the size of the icon it is being applied to. This means that small icons will have shines that are barely visible and certainly not enough dramatic effect. Is there an option to resize the shines? For example, I have a 24dp icon but I would like the shines to be bigger so they show up better. 

Thank you for all the great work and making this resource available to everyone!

**Comment by ChadCSong** [comment]
Thanks for your support. Pleasure to receive this new feature request. The shine size is calculate by button width(big shine:width/2* shine_distance_multiple; small shine:width/3* shine_distance_multiple). I will add this new feature in the near future. Thanks again.

**Comment by ChadCSong** [comment]
Custom your shine size is supported. You can have a try. If have any questions just open issues or email me.

**Comment by searchy2** [comment]
Wow, that was fast! This is a great feature to have, thank you so much! I am testing this right now but it takes a while for dependencies to update as Gradle is not finding 0.1.5

**Comment by ChadCSong** [comment]
@searchy2  It will take a few hours prepare after I upload new version. Try this version few hours later. :)  So pleasure to hear you want to donate to me, any amount will encourage me a lot. [https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=chadsong@sina.cn&currency_code=USD&item_name=Github support of ChadCSong&undefined_quantity=1](Click here)

**Comment by ChadCSong** [comment]
@searchy2 Version 0.1.5 is available now, you can try it. :)

**Comment by searchy2** [comment]
Dam it Paypal you POS! That and the 20% remittance fees :imp: 
![paypal unable to send money to china](https://cloud.githubusercontent.com/assets/19896174/17424673/ebf48404-5a8b-11e6-8e4d-4e8307d5fbf2.png)
