### ISSUE TITLE
Problem with RecyclerView

### ISSUE THREAD

**Issue by moderateepheezy** [ChadCSong/ShineButton#7]
when i click on one of the shine button and scroll away from that position, on getting back to it, it will deselect itself automatically.
How can i fix this, i notice the same thing in the example you provided for the list view

**Comment by linean** [comment]
You must remember checked state and set it again when recycler is drawing your layout :)

**Comment by moderateepheezy** [comment]
@linean please can you help me with that, i have no idea how to work that out.

**Comment by ChadCSong** [comment]
The select state is control by data. You should add flags or modify data to let view remember you state when you use listView or recyclerView. So you can try to control it by using setChecked(bool)   in callBack onBindViewHolder().
Such as:
` @Override
        public void onBindViewHolder(MyViewHolder holder, int position)
        {
            holder.shineButton.setChecked(data.get(position).isChecked());
        }
`

**Comment by moderateepheezy** [comment]
its not working, i set a flag already, this what am doing below

        });`holder.ivLike.setTag(holder);
        holder.ivLike.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                PostsViewHolder viewHolder =(PostsViewHolder) v.getTag();
                if (!isLike) {
                    like(postsData.getNews_id());
                    viewHolder.tvNewsCountLike.setText("" + (Integer.parseInt(holder.tvNewsCountLike.getText().toString()) + 1));
                    viewHolder.ivLike.setChecked(true);
                    isLike = true;
                } else {
                    unlike(postsData.getNews_id());
                    viewHolder.tvNewsCountLike.setText("" + (Integer.parseInt(holder.tvNewsCountLike.getText().toString()) - 1));
                    viewHolder.ivLike.setChecked(false);
                    isLike = false;

                }

            }
        });`

**Comment by ChadCSong** [comment]
@moderateepheezy 
Add boolean property "isLike" in PostsData.
Set this property when you click.
Add control code as follow.
`
@Override
public void onBindViewHolder(MyViewHolder holder, int position) {
     holder.shineButton.setChecked(postsDataList.get(position).isChecked());
}
`

**Comment by ChadCSong** [comment]
This is the basic knowledge of listView
