### ISSUE TITLE
Wrong animation position after fullscreen

### ISSUE THREAD

**Issue by oleynikd** [ChadCSong/ShineButton#8]
Hi,

First of all - thanks for such a great lib!

I have a problem with animation position after entering and exiting activity fullscreen mode.

In landscape mode my app goes fullscreen hiding all system UI. When I resume to portrait and exit fullscreen shining animations starts in wrong place!

Please help.

**Comment by ChadCSong** [comment]
I see an amazing app.  haha  . Sorry to reply so late, It seems a bug. I will fix it soon. Thanks.

**Comment by oleynikd** [comment]
@ChadCSong any news? Thanks.

**Comment by grzegorzgg** [comment]
@ChadCSong I have the same bug when using FLAG_TRANSLUCENT_NAVIGATION

**Comment by ChadCSong** [comment]
@oleynikd @grzegorzgg  Fix it in new version 0.1.9. Any questions contact me.
